Missing declaration for TXPAPIDLLEXP
 Added '#include "platformspecific.h" to address the compile errors:

g++ -c -pthread -Wall -Wno-switch -Wno-unused-function -std=c++11 -fPIC Decimal.cpp -I. -o Decimal.o
In file included from Decimal.cpp:5:
Decimal.h:25:20: error: variable ‘TWSAPIDLLEXP DecimalFunctions’ has initializer but incomplete type
   25 | class TWSAPIDLLEXP DecimalFunctions {
      |                    ^~~~~~~~~~~~~~~~
Decimal.h:27:1: error: expected primary-expression before ‘public’
   27 | public:
      | ^~~~~~
Decimal.h:27:1: error: expected ‘}’ before ‘public’
Decimal.h:25:37: note: to match this ‘{’
   25 | class TWSAPIDLLEXP DecimalFunctions {